Add DisplayName to the Machine description
juju/description pull request #102
Opened 2022-01-22 23:54 UTC by cderici

This adds the `DisplayName` field for a machine to transfer its display name through the migration. 

It is a pre-requisite for this PR on juju for fixing the [LP #1954969](https://bugs.launchpad.net/juju/+bug/1954969).

2022-01-24 10:15 UTC, juanmanuel-tirado approved these changes
LG2M

2022-01-24 12:54 UTC, manadart requested changes
We don't want to transport this with the machine document. It resides in the `instanceData` collection and should go against the `cloudInstance` type in this library.

2022-01-25 14:15 UTC, manadart approved these changes
Yes, this looks better.

2022-01-25 16:16 UTC, cderici commented
$$merge$$

2022-01-25 16:19 UTC, merged