Add image-id constraint
juju/description pull request #125
Opened 2023-03-15 09:39 UTC by nvinuesa

This PR adds the new image-id constraint that has been added to juju core in https://github.com/juju/juju/pull/15284.

Also, I have renamed `ImageId` cloud image metadata to `ImageID` to match golang naming style.

QA:
```sh
$ go test ./...
ok  	github.com/juju/description/v4	0.469s
```
also, `$ make check-go` passes.

2023-03-15 10:32 UTC, SimonRichardson requested changes

2023-03-15 10:32 UTC, SimonRichardson commented on constraints_test.go
> +//
Delete me

2023-03-15 10:38 UTC, nvinuesa commented on cloudimagemetadata.go
> +	ImageID_         string     `yaml:"image-id"`
Oh you are absolutely right, it's reverted now

2023-03-15 10:39 UTC, nvinuesa commented on constraints_test.go
> +//
done

2023-03-15 10:39 UTC, nvinuesa commented on interfaces.go
> +	ImageID() string
done

2023-03-16 08:56 UTC, SimonRichardson approved these changes

2023-03-16 09:15 UTC, merged